# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Surfshark.Surfshark
PackageVersion: 5.10.2.999
PackageLocale: en-US
Publisher: Surfshark
PublisherUrl: https://surfshark.com/
PublisherSupportUrl: https://support.surfshark.com/
PrivacyUrl: https://surfshark.com/privacy
Author: Surfshark B.V.
PackageName: Surfshark
PackageUrl: https://surfshark.com/
License: Proprietary
LicenseUrl: https://surfshark.com/terms-of-service
Copyright: © 2024 Surfshark. All rights reserved.
ShortDescription: Surf the web without tracking with a VPN, shield your devices with Antivirus, & guard your identity with an all-in-one app.
Moniker: surfshark
Tags:
- network
- privacy
- proxy
- security
- vpn
PurchaseUrl: https://surfshark.com/pricing
ManifestType: defaultLocale
ManifestVersion: 1.6.0
